#!/usr/bin/env ruby
#
# Description: Decrypts a file encrypted via OpenSSL.
# Author: Guy Dalziel
#
require 'optparse'

options = {noretain:true} # Set default values for conditional handling
OptionParser.new do |opts|
  opts.banner = "Usage: decrypt [options] <filename.aes>"

  opts.separator ""
  opts.separator "Options:"

  opts.on("-r", "--retain", "Retain original file after decryption.") do |r|
    options[:noretain] = r
  end
end.parse!

if ARGV.count == 0
    puts "No arguments provided. Please provide a filename"
    exit
elsif ARGV.count == 1
  filename = ARGV[0]
elsif ARGV.count > 1
  puts "Error: too many arguments"
  exit
end

input = filename.dup
input.gsub!(/\s/,'\ ')
output = input.gsub('.aes','')

system("openssl aes-256-cbc -d -a -p -md sha1 -in #{input} -out #{output} > /dev/null")

if options[:noretain] == true
    File.delete(filename)
end
