#!/usr/bin/env ruby
#
# Title:       encrypt
# Description: Encrypts a specified file via OpenSSL.
# Author:      Guy Dalziel
# Date:        20181206
# Version:     1.0.0
#

if ARGV.count == 0
    puts "No arguments provided. Please provide a filename"
    exit
elsif ARGV.count == 1
  filename = ARGV[0]
elsif ARGV.count > 1
  puts "Error: too many arguments"
  exit
end

input = filename.dup
input.gsub!(/\s/,'\ ')
output = input.sub(/$/,'.aes')

`openssl aes-256-cbc -e -a -p -md sha1 -in #{input} -out #{output}`
